
ami 		= "ami-0fad7378adf284ce0"
instance_type   = "t2.micro"
key_name 	= "testkey"
Name		= "solar"
Created_by 	= "Aiza"
count 		= "2"
vpc		= "vpc-5674d530"
env		= "UAT"
name 		= "solar.dev.company.com"
Department	= "IT"
